server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: subscriptionRoute
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscription/**
          filters:
            - name: SubscriptionFilter
        - id: courseRoute
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
          filters:
                - AddRequestHeader=course-request-header, custom-course-request-header
                - AddResponseHeader=course-response-header, custom-course-response-header
