server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: subscriptionRoute
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscription/**
          filters:
            - name: SubscriptionFilter
        - id: courseRoute
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
