server:
  port: 8080
spring:
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
  cloud:
    gateway:
      routes:
        - id: catalogoRoute
          uri: lb://CATALOGO-SERVICE
          predicates:
            - Path=/catalogo/**
        - id: filmeRoute
          uri: lb://FILME-SERVICE
          predicates:
            - Path=/filme/**
        - id: seriesRoute
          uri: lb://SERIE-SERVICE
          predicates:
            - Path=/series/**
        - id: temporadasRoute
          uri: lb://SERIE-SERVICE
          predicates:
            - Path=/temporadas/**
        - id: capitulosRoute
          uri: lb://SERIE-SERVICE
          predicates:
            - Path=/capitulos/**
